FROM python:3.11-slim

WORKDIR /app

COPY nlp-service/requirements.txt .

# Install Python dependencies including spaCy model
RUN pip install --no-cache-dir --default-timeout=1000 -r requirements.txt

COPY nlp-service/ .

EXPOSE 8000

CMD ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
