# Build stage
FROM node:18-bullseye as builder

WORKDIR /app

COPY frontend/package*.json ./

RUN npm install --force --no-optional

COPY frontend/ .

ENV SKIP_PREFLIGHT_CHECK=true
ENV GENERATE_SOURCEMAP=false

RUN npm run build

# Production stage
FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html

COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
